import { defineAsyncComponent } from 'vue'
import type { GameConfig } from '@/types'

export const GAMES: GameConfig[] = [
  {
    id: 'direction-quix',
    titleKey: 'directionQuix.title',
    descriptionKey: 'directionQuix.description',
    icon: '🧭',
    color: 'from-violet-500 to-purple-600',
    path: '/game/direction-quix',
    component: defineAsyncComponent(() => import('@/components/games/DirectionQuix.vue')),
  },
  {
    id: 'missing-letter',
    titleKey: 'missingLetter.title',
    descriptionKey: 'missingLetter.description',
    icon: '📝',
    color: 'from-emerald-500 to-teal-600',
    path: '/game/missing-letter',
    component: defineAsyncComponent(() => import('@/components/games/MissingLetter.vue')),
  },
  {
    id: 'mystical-times-table',
    titleKey: 'mysticalTimesTable.title',
    descriptionKey: 'mysticalTimesTable.description',
    icon: '🔮',
    color: 'from-indigo-500 to-purple-700',
    path: '/game/mystical-times-table',
    component: defineAsyncComponent(() => import('@/components/games/MysticalTimesTable.vue')),
  },
  {
    id: 'mystical-division-oracle',
    titleKey: 'mysticalDivisionOracle.title',
    descriptionKey: 'mysticalDivisionOracle.description',
    icon: '✨',
    color: 'from-cyan-500 to-blue-600',
    path: '/game/mystical-division-oracle',
    component: defineAsyncComponent(() => import('@/components/games/MysticalDivisionOracle.vue')),
  },
  {
    id: 'it-hardware-quiz',
    titleKey: 'itHardwareQuiz.title',
    descriptionKey: 'itHardwareQuiz.description',
    icon: '💻',
    color: 'from-sky-500 to-blue-600',
    path: '/game/it-hardware-quiz',
    component: defineAsyncComponent(() => import('@/components/games/ItHardwareQuiz.vue')),
  },
  {
    id: 'bundeslaender-quiz',
    titleKey: 'bundeslaenderQuiz.title',
    descriptionKey: 'bundeslaenderQuiz.description',
    icon: '🗺️',
    color: 'from-amber-500 to-orange-600',
    path: '/game/bundeslaender-quiz',
    component: defineAsyncComponent(() => import('@/components/games/BundeslaenderQuiz.vue')),
  },
  {
    id: 'clock-detective',
    titleKey: 'clockDetective.title',
    descriptionKey: 'clockDetective.description',
    icon: '🕰️',
    color: 'from-sky-400 to-cyan-600',
    path: '/game/clock-detective',
    component: defineAsyncComponent(() => import('@/components/games/ClockDetective.vue')),
  },
  {
    id: 'language-detective',
    titleKey: 'languageQuiz.title',
    descriptionKey: 'languageQuiz.description',
    icon: '🕵️',
    color: 'from-fuchsia-500 to-pink-600',
    path: '/game/language-detective',
    component: defineAsyncComponent(() => import('@/components/games/LanguageDetective.vue')),
  },
  {
    id: 'sequence-train',
    titleKey: 'sequenceTrain.title',
    descriptionKey: 'sequenceTrain.description',
    icon: '🚂',
    color: 'from-orange-500 to-red-500',
    path: '/game/sequence-train',
    component: defineAsyncComponent(() => import('@/components/games/SequenceTrain.vue')),
  },
]
